ARG VARIANT=latest
FROM thommyho1988/docker-devcontainer-builder-ubuntu2004:${VARIANT}

USER vscode

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
